<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => '九成新 微積分原文書 (Calculus Early Transcendentals)',
                'description' => '大一微積分神書！幾乎沒有劃記，約九成新。附贈幾份期中考考古題，面交限校內圖書館前。',
                'price' => 700,
                'stock' => 1,
                'category_id' => 1, 
                'image_url' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=800&auto=format&fit=crop',
                'view_count' => 15,
            ],
            [
                'name' => '二手 iPad Air 4 (64G 天空藍) 附 Apple Pencil',
                'description' => '已過保固，平時都裝犀牛盾所以外觀無傷。電池健康度約 88%，上課做筆記超級方便！畢業故售出。',
                'price' => 12500,
                'stock' => 1,
                'category_id' => 2, 
                'image_url' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop',
                'view_count' => 128,
            ],
            [
                'name' => 'IKEA 白色網格辦公椅 (可旋轉)',
                'description' => '宿舍空間太小放不下，僅使用一學期，氣壓棒升降正常。這張椅子原價快兩千，便宜賣給學弟妹，需自取。',
                'price' => 500,
                'stock' => 1,
                'category_id' => 3, 
                'image_url' => 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?q=80&w=800&auto=format&fit=crop',
                'view_count' => 42,
            ],
            [
                'name' => '捷安特 Giant 二手變速腳踏車',
                'description' => '校園代步必備神車！煞車剛換過新的，輪胎胎痕還很深。車鎖會直接送給你。',
                'price' => 1200,
                'stock' => 1,
                'category_id' => 5, 
                'image_url' => 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=800&auto=format&fit=crop',
                'view_count' => 89,
            ],
            [
                'name' => '全新未拆封 無印良品 MUJI 筆記本 (5入組)',
                'description' => '之前不小心買太多，全新完全沒拆封過。原價一組 150，現在隨便賣。',
                'price' => 100,
                'stock' => 3, 
                'category_id' => 1, 
                'image_url' => 'https://images.unsplash.com/photo-1531346878377-a541e4ab0e37?q=80&w=800&auto=format&fit=crop',
                'view_count' => 5,
            ],
            [
                'name' => '線性代數與微分方程 (第六版)',
                'description' => '大二必修教科書，有劃重點但不影響閱讀。包含習題解答和考試重點整理，真的超有幫助！',
                'price' => 550,
                'stock' => 2,
                'category_id' => 1,
                'image_url' => 'https://images.unsplash.com/photo-1516979187457-635ffe35ff91?q=80&w=800&auto=format&fit=crop',
                'view_count' => 23,
            ],
            [
                'name' => '有機化學 (Morrison & Boyd)',
                'description' => '系規定的原文書，約七成新。雖然有些筆記但考試範圍都有標註，省去翻書時間。',
                'price' => 650,
                'stock' => 1,
                'category_id' => 1,
                'image_url' => 'https://images.unsplash.com/photo-1532995122724-8a15fb778444?q=80&w=800&auto=format&fit=crop',
                'view_count' => 31,
            ],
            [
                'name' => '日文能力考 N3 參考書套組',
                'description' => '三本合售（文法、讀解、聽解），幾乎沒用過。有兩個月內的課程用不到。',
                'price' => 400,
                'stock' => 1,
                'category_id' => 1,
                'image_url' => 'https://images.unsplash.com/photo-1507842217343-583684e55c15?q=80&w=800&auto=format&fit=crop',
                'view_count' => 8,
            ],
            [
                'name' => '二手 iPhone 13 Pro Max (256G 銀色)',
                'description' => '去年買的，用了一年多。無摔過，沒裂痕。屏幕有點燒屏但不明顯。附原廠盒子和充電線，電池健康度 82%。',
                'price' => 22000,
                'stock' => 1,
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1511707267537-b85faf00021e?q=80&w=800&auto=format&fit=crop',
                'view_count' => 156,
            ],
            [
                'name' => '防水藍牙喇叭 (Bose SoundLink)',
                'description' => '能連接多個設備，音質超好！打掃衛生或運動時都好用。因為買了新的所以出售。',
                'price' => 2200,
                'stock' => 1,
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1589003077984-894e133814c9?q=80&w=800&auto=format&fit=crop',
                'view_count' => 67,
            ],
            [
                'name' => '機械鍵盤 (Cherry MX 紅軸)',
                'description' => '打遊戲打報告都超順！幾乎沒用過，買太多鍵盤了。還附贈 USB 線。',
                'price' => 1800,
                'stock' => 1,
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1587829191301-7ce2f3361e77?q=80&w=800&auto=format&fit=crop',
                'view_count' => 45,
            ],
            [
                'name' => '4K 網路攝影機 (監視用)',
                'description' => '宿舍安全防護用，已廢用。裝置完整，使用方便。有說明書和安裝教程。',
                'price' => 1500,
                'stock' => 1,
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=800&auto=format&fit=crop',
                'view_count' => 19,
            ],
            [
                'name' => '宜家 IKEA 雙人床墊',
                'description' => '買了沒多久就要搬家了，八成新。包裝完整，只需寄送。異味已經散去。',
                'price' => 2800,
                'stock' => 1,
                'category_id' => 3,
                'image_url' => 'https://images.unsplash.com/photo-1540932239986-310128078ceb?q=80&w=800&auto=format&fit=crop',
                'view_count' => 52,
            ],
            [
                'name' => '木質書架 (五層)',
                'description' => '約 2 公尺高，放書超多。我家沒地方放，整理得很乾淨。需自取。',
                'price' => 1200,
                'stock' => 1,
                'category_id' => 3,
                'image_url' => 'https://images.unsplash.com/photo-1507842217343-583684e55c15?q=80&w=800&auto=format&fit=crop',
                'view_count' => 34,
            ],
            [
                'name' => '桌下加熱器 (冬天必備)',
                'description' => '冬天課程結束不需要了，八成新。暖度剛剛好，超舒適的。',
                'price' => 380,
                'stock' => 2,
                'category_id' => 3,
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800&auto=format&fit=crop',
                'view_count' => 28,
            ],
            [
                'name' => '日光燈 LED 護眼檯燈',
                'description' => '保護眼睛超重要！用過一個月，亮度可調。原價六百多，便宜出。',
                'price' => 320,
                'stock' => 1,
                'category_id' => 3,
                'image_url' => 'https://images.unsplash.com/photo-1565636192335-14ecf9266afd?q=80&w=800&auto=format&fit=crop',
                'view_count' => 15,
            ],
            [
                'name' => '折疊式洗衣籃',
                'description' => '宿舍根本沒用過。全新未使用，就是放在角落佔空間。',
                'price' => 80,
                'stock' => 3,
                'category_id' => 3,
                'image_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800&auto=format&fit=crop',
                'view_count' => 5,
            ],
            [
                'name' => 'UNIQLO 冬季外套 (黑色 M號)',
                'description' => '質感很好的黑色外套，穿過幾次。已洗淨沒有異味，換季故出售。',
                'price' => 350,
                'stock' => 1,
                'category_id' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1539533057440-7814a9755a09?q=80&w=800&auto=format&fit=crop',
                'view_count' => 41,
            ],
            [
                'name' => 'Nike 運動鞋 (US 10 白)',
                'description' => '跑步穿過幾次，新鞋剛到所以出售舊的。沒有磨損，鞋盒附上。',
                'price' => 1200,
                'stock' => 1,
                'category_id' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop',
                'view_count' => 78,
            ],
            [
                'name' => 'CK 牛仔褲 (32 腰)',
                'description' => '正品 Calvin Klein，穿過幾次就買錯尺寸了。完整皮牌，沒洗過幾次。',
                'price' => 600,
                'stock' => 1,
                'category_id' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1542272604-787c62e4beeb?q=80&w=800&auto=format&fit=crop',
                'view_count' => 22,
            ],
            [
                'name' => '登山背包 60L',
                'description' => '登山社活動用過幾次，背帶新新的。適合戶外活動或長途旅行。',
                'price' => 1500,
                'stock' => 1,
                'category_id' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop',
                'view_count' => 36,
            ],
            [
                'name' => '兒童滑板車 (三輪)',
                'description' => '表弟用過一陣子，輪子還很新。交給更小的小孩用。',
                'price' => 400,
                'stock' => 1,
                'category_id' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1600804304289-6fab5d332b5c?q=80&w=800&auto=format&fit=crop',
                'view_count' => 12,
            ],
            [
                'name' => '滑冰鞋 (成人 M 號)',
                'description' => '冬季滑冰一陣子就買了新的，舊的沒有穿過。附頭盔和護具。',
                'price' => 1100,
                'stock' => 1,
                'category_id' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1564429015605-cb5fb5d47661?q=80&w=800&auto=format&fit=crop',
                'view_count' => 18,
            ],
            [
                'name' => '全新未用 雷鳥牌 咖啡機',
                'description' => '朋友送的禮物，我已經有一台了。盒子完整，真的沒拆過。',
                'price' => 2500,
                'stock' => 1,
                'category_id' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?q=80&w=800&auto=format&fit=crop',
                'view_count' => 55,
            ],
            [
                'name' => '蘋果削皮器 + 砧板組合',
                'description' => '團購買的，用了三天就買齊廚房用品了。還在原始包裝裡。',
                'price' => 120,
                'stock' => 2,
                'category_id' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1578500494198-246f612d03b3?q=80&w=800&auto=format&fit=crop',
                'view_count' => 8,
            ],
            [
                'name' => '飛利浦電動牙刷 (USB 充電)',
                'description' => '買了才發現牙套不適合用電動牙刷，全新未使用過。真的超新。',
                'price' => 680,
                'stock' => 1,
                'category_id' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1579154204601-01d5e82c5a0a?q=80&w=800&auto=format&fit=crop',
                'view_count' => 25,
            ],
            [
                'name' => '專業美妝梳妝鏡 (LED 燈)',
                'description' => '化妝師等級的鏡子，分辨率超清楚。因為搬家太重放棄帶。',
                'price' => 1800,
                'stock' => 1,
                'category_id' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=800&auto=format&fit=crop',
                'view_count' => 44,
            ],
            [
                'name' => '鐵三角耳機 (降噪型)',
                'description' => '通勤上課戴過幾次，電池還超新。降噪效果一級棒，出差不需要了。',
                'price' => 2100,
                'stock' => 1,
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
                'view_count' => 92,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}